### ISSUE TITLE
Implement support for OkHttp

### ISSUE THREAD

**Issue by petrdvorak** [wultra/ssl-pinning-android#1]
We can enhance the SSL pinning support on Android by implementing some high-level support for integration in OkHttp, which is the most common networking framework on Android.

**Comment by TomasKypta** [comment]
The support for OkHttp has been already added.

For integrating with OkHttp there are `SSLPinningIntegration` and `SSLPinningX509TrustManager` classes. You can integrate it this way:
```kotlin
val okhttpClient = OkHttpClient.Builder()
                .sslSocketFactory(sslSocketFactory, trustManager)
                .build()
```

We don't support OkHttp's [`CertificatePinner`](https://square.github.io/okhttp/3.x/okhttp/okhttp3/CertificatePinner.html) since it uses public key pinning. But WultraSSLPinning uses certificate pinning. See [README](https://github.com/wultra/ssl-pinning-android/blob/develop/README.md) and [FAQ](https://github.com/wultra/ssl-pinning-android/blob/develop/README.md#faq) for more info.
